server:
  port: 8080
  max-http-header-size: 102400000
  undertow:
    max-http-post-size: 102400000
    url-charset: utf-8

spring:
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      jdbc-url: jdbc:clickhouse://ip:port/database
      username: default
      password: password
      #最大建立连接等待时间。如果超过此时间将接到异常，单位毫秒
      maxWait: 8000
      initialSize: 10
      minIdle: 50
      maxIdle: 250
      maxActive: 300
      removeAbandoned: true
      #从getconn到sql执行完，超过10秒会被释放
      removeAbandonedTimeout: 10


#  mvc:
#    view:
#      prefix:  /
#      suffix: .html

mybatis:
  mapper-locations: classpath*:com/office/export/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
  # mybatis自带日志打印 本地调试可以放开

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: ck # 设置数据库类型
  reasonable: true #开启合理化：页码<=0 查询第一页，页码>=总页数查询最后一页
  supportMethodsArguments: true #支持通过 Mapper 接口参数来传递分页参数
  params: count=countSql   # 参数  成员变量 = ${ xx}
  offsetAsPageNum: true #该参数默认为false 设置为true时，会将RowBounds第一个参数offset当成pageNum页码使用,和startPage中的pageNum效果一样
  rowBoundsWithCount: true #设置为true时，使用RowBounds分页会进行count查询
  returnPageInfo: true #总是返回PageInfo类型,check检查返回类型是否为PageInfo,none返回Page


logging:
  level:
    com.office.export: debug

